### ISSUE TITLE
Typos in indicator doctrings

### ISSUE THREAD

**Issue by shipmints** [tarsius/mode-line-debug#1]
Thank you for this package. Saved me a few minutes not writing my own.

The indicator docstrings say off twice. Confused me for a few seconds. PR incoming.

**Comment by tarsius** [comment]
Thanks!

Please don't add an issue and a pull-request per change.  That "best practice" just means more busy work for me.  There also is no need to create separate pull-requests for trivial changes, just add them to another pull-request (but do use a separate commit).  What qualifies as trivial is of course subjective, but typo fixes definitely are.

**Comment by shipmints** [comment]
No problem. Many people prefer individual changes to aid testing. I will likely have no more changes for this package. It's tiny, fit-for-purpose, and now, perfect.

**Comment by shipmints** [comment]
Also, THANK YOU FOR MAGIT and everything else, of course.
