### ISSUE TITLE
Optional mode-line prefix string to help identify mode-line-misc-info entry

### ISSUE THREAD

**Issue by shipmints** [tarsius/mode-line-debug#5]
I set mine to 
```elisp
  (setq mode-line-debug-prefix "🐞")
```

PR incoming.

**Comment by tarsius** [comment]
That's cute, but IMO it's neither necessary nor sufficient.

Another user may wish to *append* something, or put something before *and* after the three characters, or capitalize them, or format them differently altogether.  I don't want to cover one random variant nor make this super flexible.

You can achieve the same using a simple advice:

``` emacs-lisp
(define-advice mode-line-debug-control (:around (fn) ladybird)
  (cons "🐞" (funcall fn)))
```

**Comment by shipmints** [comment]
Alrighty, then. Advice taken and implemented.
